Bruker familie prosessering
navikt/familie-ba-sak pull request #1342
Opened 2021-08-20 16:27 UTC by MengZhuNAV

### 💰 Hva forsøker du å løse i denne PR'en
Use familie-prosessering for task control

### 🔎️ Er det noe spesielt du ønsker å fremheve?

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [ ] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [X] Jeg har config eller sql endringer. Isåfall, husk manuell deploy til miljø for å verifisere endringene.
- [ ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

_Jeg har ikke skrevet tester fordi:_
N/A

### 🤷‍♀ ️Hvor er det lurt å starte?
alt_i_ett

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [X] Nei

2021-08-23 08:32 UTC, blommish reviewed
Ser fint ut.
Det er litt forskjell i formattering, så sikkert fint å ta en runde på de diffene etter att man tatt inn siste versjon av familie-settings.
I tillegg er jeg litt usikker på om man virkelig trenger å dra inn biblioteket reflections

2021-08-23 08:32 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/task/GrensesnittavstemMotOppdrag.kt
> +            MonthDay.of(1, 1),
Unødvendig diff, husk å gå igjennom alle filer etter att du har oppdatert familie-settings :)

2021-08-23 08:32 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/task/OpprettOppgaveTask.kt
> +        taskRepository.save(task)
Jeg vet vi også gjører det samme noen steder. Men husk her att prosessering også lagrer ned tasken etterpå. Sånn att hvis man hadde endret noe annet enn metadata på tasken, så blir det overskrevet senere i `TaskWorker`
```
task = task.ferdigstill()
taskService.save(task)
```

2021-08-23 08:32 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/task/SendAutobrev6og18ÅrTask.kt
> -                     feiletStatus = Status.MANUELL_OPPFØLGING)
Akkurat denne finnes det ikke støtte for i nye prosessering, men `settTilManuellOppfølgning = true` finnes :)

2021-08-23 08:32 UTC, blommish commented on src/main/resources/db/migration/V9__prosessering.sql
> +CREATE SEQUENCE IF NOT EXISTS task_seq INCREMENT BY 50;
Går det å endre en tidligere versjon? Tror de lagres med en hash i databasen og her blir den vel endret?

2021-08-23 08:32 UTC, blommish commented on src/main/resources/db/migration/V149__prosessering_jdbc_patch.sql
> +ALTER SEQUENCE task_logg_seq OWNED BY task_logg.id;
👍

2021-08-23 08:32 UTC, blommish commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggServiceTest.kt
> +    @Sql(scripts = ["classpath:db/migration/V9__prosessering.sql"], executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
Annotasjonen `@Sql` kan slettes her

2021-08-23 10:03 UTC, hensol reviewed
Må si dette er en solid PR, veldig bra at det taes tak i å gå over til felles prosessering backend. Bra jobba :)

Har lagt inn noen kommentarer, også kan det være greit å få på plass riktig familie-settings og kjøre en ny formattering på endrede filer.

2021-08-23 10:03 UTC, hensol commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggServiceTest.kt
> +    @Sql(scripts = ["classpath:db/migration/V9__prosessering.sql"], executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
må huske på å ta med migreringsscriptet for ny sekvens, eller lage ett eget script for tasks under test scope.

2021-08-24 07:12 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/config/KafkaAivenConfig.kt
> +import org.springframework.kafka.core.*
Ok!

2021-08-24 07:18 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/config/e2e/DatabaseCleanupService.kt
> +        val ref = Reflections("no.nav.familie")
Yes, because entityManager.metamodel.managedTypes only include the entities annotated with JPA. The Task and TaskLogg are not managed by JPA EntityManage, which should also be added to the table names
The Reflections library is a solution I found by google, and I do not know if there is a more suitable solution. Do you have any suggestions?

2021-08-24 07:19 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/task/GrensesnittavstemMotOppdrag.kt
> +            MonthDay.of(1, 1),
Ok!

2021-08-24 07:20 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/task/OpprettOppgaveTask.kt
> +        taskRepository.save(task)
I think it is safe

2021-08-24 07:23 UTC, MengZhuNAV commented on src/main/resources/db/migration/V149__prosessering_jdbc_patch.sql
> +ALTER SEQUENCE task_logg_seq OWNED BY task_logg.id;
Yes, I think the sequence was connected to the id automatically with JPA, but it has to be done manually for JDBC tables

2021-08-24 07:24 UTC, MengZhuNAV commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggServiceTest.kt
> +    @Sql(scripts = ["classpath:db/migration/V9__prosessering.sql"], executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
I forgot to delete it, sorry

2021-08-24 07:25 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/KonsistensavstemmingScheduler.kt
> +        val konsistensavstemmingTask = Task(
Agree, and I'll fix it!

2021-08-24 23:24 UTC, MengZhuNAV commented on src/main/resources/db/migration/V9__prosessering.sql
> +CREATE SEQUENCE IF NOT EXISTS task_seq INCREMENT BY 50;
I think this change won't be a problem, but anyway I added a new script to make it safe:)

2021-08-30 09:33 UTC, ninakjek commented
Veldig bra jobba, @MengZhuNAV 👏  jeg har ikke noe å føye til, men det var lærerikt å se gjennom alt du har gjort :)

2021-08-30 09:45 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/task/SendAutobrev6og18ÅrTask.kt
> -                     feiletStatus = Status.MANUELL_OPPFØLGING)
Remember to add the field Johan is refering to here @MengZhuNAV :)

2021-08-30 09:46 UTC, henninghaakonsen commented on src/main/resources/db/migration/V149__prosessering_jdbc.sql
> +    metadata      VARCHAR(4000),
Would TEXT be better here? If the length is varying I mean :)

2021-08-30 09:47 UTC, henninghaakonsen commented on src/main/resources/db/migration/V149__prosessering_jdbc.sql
> +CREATE TABLE IF NOT EXISTS task (
We don't need to explicitly set the size of varchars, postgres will only use the length of the field anyways.

2021-08-30 09:47 UTC, henninghaakonsen commented on src/main/resources/db/migration/V150__prosessering_jdbc_patch.sql
> +ALTER TABLE task ALTER COLUMN id SET DEFAULT nextval('task_seq');
If you have not deployed this branch yet, you can just update V149 :)

2021-08-30 09:48 UTC, henninghaakonsen commented on src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
>  class MigreringServiceTest : AbstractSpringIntegrationTestDev() {
We should use `AbstractSpringIntegrationTest` instead of dev if we want to use postgres in the test.

2021-08-30 09:50 UTC, henninghaakonsen requested changes
Great work, I have left some comments I think we should improve before merge. Also it would be great if you updated the styling so that we don't have the big diff :)

2021-08-30 09:50 UTC, henninghaakonsen commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggServiceTest.kt
> +        dataSource.getConnection().use { conn ->
Why do we need this?

2021-08-30 20:39 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/task/SendAutobrev6og18ÅrTask.kt
> -                     feiletStatus = Status.MANUELL_OPPFØLGING)
Ok!

2021-08-30 20:41 UTC, MengZhuNAV commented on src/main/resources/db/migration/V149__prosessering_jdbc.sql
> +    metadata      VARCHAR(4000),
Ok

2021-08-30 20:41 UTC, MengZhuNAV commented on src/main/resources/db/migration/V149__prosessering_jdbc.sql
> +CREATE TABLE IF NOT EXISTS task (
Ok

2021-08-30 20:41 UTC, MengZhuNAV commented on src/main/resources/db/migration/V150__prosessering_jdbc_patch.sql
> +ALTER TABLE task ALTER COLUMN id SET DEFAULT nextval('task_seq');
Ok

2021-08-30 20:42 UTC, MengZhuNAV commented on src/test/kotlin/no/nav/familie/ba/sak/integrasjoner/infotrygd/MigreringServiceTest.kt
>  class MigreringServiceTest : AbstractSpringIntegrationTestDev() {
Ok, thank you for letting me know the trick

2021-08-30 20:43 UTC, MengZhuNAV commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/logg/LoggServiceTest.kt
> +        dataSource.getConnection().use { conn ->
we need it to execute the sql to create Task tables

2021-09-01 06:41 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/config/e2e/DatabaseCleanupService.kt
> +        val ref = Reflections("no.nav.familie")
I think you might be able to use the bean `private val context: RelationalMappingContext`
And then use `context.persistentEntities.first().tableName`

2021-09-01 06:44 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/task/OpprettOppgaveTask.kt
> +        taskRepository.save(task)
Det burde egentlige ikke være mulig då versjon i Task er annotert med @Version, sånn att den burde kaste feil senere når prosessering-lib skal lage den samme tasken og den har missmatch på versjon?

2021-09-01 12:42 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/config/e2e/DatabaseCleanupService.kt
> +        val ref = Reflections("no.nav.familie")
Yes I tried and it works! Thank you for letting me know this method.
But RelationalMappingContext does not hold the entities in afterPropertiesSet(), so I have to use lazy initialization to refactor the field. Please have a look at the code for details

2021-09-02 06:46 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/task/OpprettOppgaveTask.kt
> +        taskRepository.save(task)
@blommish You are right👍  Confirmed with a test that the save() inside doTask() will generate an optimistic lock error.
I think the save() could be deleted since I did not see anywhere in the code that the task was retrieved from repository after the save(), and the task will be saved anyway in TaskWorker.doActualWork()
I'll check with people who knows the task

2021-09-06 06:37 UTC, henninghaakonsen commented on src/main/resources/db/migration/V150__prosessering_jdbc_patch.sql
> +ALTER TABLE task ALTER COLUMN id SET DEFAULT nextval('task_seq');
If you moved V149 to test scope this should be renamed to V149 :)

2021-09-06 06:37 UTC, henninghaakonsen commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjonTest.kt
> +@Disabled
Why is this disabled?

2021-09-06 06:40 UTC, henninghaakonsen approved these changes

2021-09-06 07:11 UTC, MengZhuNAV commented on src/main/resources/db/migration/V150__prosessering_jdbc_patch.sql
> +ALTER TABLE task ALTER COLUMN id SET DEFAULT nextval('task_seq');
Yeah, but someone added another V149 to master before I merge:)

2021-09-06 07:15 UTC, MengZhuNAV commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/vedtak/begrunnelser/VedtakBegrunnelseSpesifikasjonTest.kt
> +@Disabled
I forgot to remove it. Sorry!

2021-09-16 07:28 UTC, merged