Legg til avtale og søknadstidspunkt
navikt/familie-ba-sak pull request #1479
Opened 2021-10-01 11:57 UTC by MarcusGustafson74

### 💰 Hva forsøker du å løse i denne PR'en
Legg til to nye felt til avtale og søknadstidspunkt til endret utbetaling andel.
Se: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6600

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [X] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [X] Jeg har config eller sql endringer. Isåfall, husk manuell deploy til miljø for å verifisere endringene.
- [/] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

_Jeg har ikke skrevet tester fordi:_
Attributtene styrer ikke noen logikk og det er derfor inget å teste.

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [X] Nei

2021-10-01 12:11 UTC, henninghaakonsen requested changes
Kan ta en muntlig sync om dette på mandag om du vil.

2021-10-01 12:11 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestEndretUtbetalingAndel.kt
> +    val søknadstidspunkt: YearMonth?,
Er det litt rart at "metadata" knyttet til én årsak ligger på denne dataklassen? Er det mulig å gjøre noe smart her avhengig av årsak?

2021-10-01 12:11 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt
> +    @Column(name = "avtaletidspunkt")
Samme her tenker jeg, hvis vi får mange årsaker med ulike "skjemadata" så blir dette litt vanskelig å forholde seg til senere.

2021-10-01 12:46 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/ekstern/restDomene/RestEndretUtbetalingAndel.kt
> +    val søknadstidspunkt: YearMonth?,
Søknadstidspunkt gjelder alle typer men avtaletidpunkt gjelder bare del bosted, jeg kan se på hva man kan gjøre.

2021-10-04 07:03 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/endretutbetaling/domene/EndretUtbetalingAndel.kt
> +    @Column(name = "avtaletidspunkt")
Se svar på kommentar ovenfor.

2021-10-04 07:05 UTC, henninghaakonsen approved these changes

2021-10-04 13:48 UTC, merged