håndterte iverksettelse for migreringsbehandling slik at den kan avsluttes med automatisk totrinnskontroll og sender ikke brev
navikt/familie-ba-sak pull request #1735
Opened 2021-11-30 12:34 UTC by haldersaikat

### 💰 Hva forsøker du å løse i denne PR'en
_Skriv 1 eller 2 setninger om hvilken funksjonell endring som blir implementert._
håndterte iverksettelse for migreringsbehandling slik at den kan avsluttes med automatisk totrinnskontroll og sender ikke brev

### 🔎️ Er det noe spesielt du ønsker å fremheve?
_Er det noe du er bekymret eller usikker på? Beskriv det gjerne her._

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [ x] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [ ] Jeg har config eller sql endringer. Isåfall, husk manuell deploy til miljø for å verifisere endringene.
- [ ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

_Jeg har ikke skrevet tester fordi:_

### 🤷‍♀ ️Hvor er det lurt å starte?
_F.eks. commit for commit, alt i ett?_

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [ ] Nei

2021-11-30 12:52 UTC, henninghaakonsen reviewed
Noen justeringer, men ser fint ut :)

2021-11-30 12:52 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt
> +        if (behandling.erManuellMigrering()) {
Tror kanskje jeg ville flyttet dette til stegServicen ettersom hver steg ligger under transactional. Hvis det nå feiler i håndterBeslutningForVedtak rulles ikke alt tilbake.

2021-11-30 12:52 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
>      fun erBehandlingMedVedtaksbrevutsending(): Boolean {
Kanskje vi kunne skrevet en test på denne metoden nå ettersom den er ganske kritisk og det er flere årsaker til at man ikke ønsker å sende ut brev :)

2021-11-30 12:52 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
> +                else -> throw IllegalStateException("StegType ${utførendeStegType.displayName()} ugyldig ved migrering")
Kanskje endre på meldingen her.

2021-11-30 12:52 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt
> +            beslutter = if (behandling.erManuellMigrering()) SikkerhetContext.SYSTEM_NAVN else
Dette tenker jeg vi bør ha en test på. Kan også vurdere å lage egen metode for å beslutte som system.

2021-11-30 13:06 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
> +                else -> throw IllegalStateException("StegType ${utførendeStegType.displayName()} ugyldig ved migrering")
Kan du foreslå noe :-)?

2021-11-30 15:25 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt
> +        if (behandling.erManuellMigrering()) {
fikset denne, når kaller jeg begge to via håndterSendTilBeslutter

2021-11-30 15:25 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BeslutteVedtak.kt
> +            beslutter = if (behandling.erManuellMigrering()) SikkerhetContext.SYSTEM_NAVN else
testet det med StegServiceTest

2021-12-01 12:31 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
> +                else -> throw IllegalStateException("StegType ${utførendeStegType.displayName()} ugyldig ved migrering")
ugyldig ved endre migreringsdato

2021-12-01 12:34 UTC, henninghaakonsen requested changes
Noen ting som bør endres før denne går inn :)

2021-12-01 12:34 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
> +        val behandlingEtterBeslutterSteg = håndterSendTilBeslutter(behandling, behandlendeEnhet)
Denne må ikke brukes av andre og jeg tenker det er fint med en sperre på at den kun slipper gjennom behandlinger av den gitte typen.

2021-12-01 12:34 UTC, henninghaakonsen commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
> +    fun `skal kjøre gjennom steg for migreringsbehandling`() {
```suggestion
    fun `skal kjøre gjennom steg for endre migreringsdato behandling`() {
```

2021-12-01 12:34 UTC, henninghaakonsen commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
> +        assertTrue {
Denne ville jeg splittet opp i flere assertEquals tror jeg :)

2021-12-01 12:55 UTC, haldersaikat commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
> +    fun `skal kjøre gjennom steg for migreringsbehandling`() {
fikset

2021-12-01 12:55 UTC, haldersaikat commented on src/test/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegServiceTest.kt
> +        assertTrue {
fikset

2021-12-01 12:56 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/StegService.kt
> +        val behandlingEtterBeslutterSteg = håndterSendTilBeslutter(behandling, behandlendeEnhet)
Som diskutert er sjekken allerede på plass. Fjernet ekstra metode :-)

2021-12-01 12:56 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/steg/BehandlingSteg.kt
> +                else -> throw IllegalStateException("StegType ${utførendeStegType.displayName()} ugyldig ved migrering")
fikset

2021-12-01 13:12 UTC, haldersaikat commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/domene/Behandling.kt
>      fun erBehandlingMedVedtaksbrevutsending(): Boolean {
la til tester

2021-12-01 13:14 UTC, henninghaakonsen approved these changes
👏

2021-12-01 13:27 UTC, merged