Send VedtakV2 to Kafka Aiven topic for DVH, enabled only in preprod
navikt/familie-ba-sak pull request #2455
Opened 2022-05-12 18:13 UTC by MengZhuNAV

Send VedtakV2 to Kafka Aiven topic, which should have been deployed
Only enabled in preprod
The Vedtak will still be sent to the on-prem topic

2022-05-13 09:08 UTC, halvorbmundal commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +    override fun sendMessageForTopicVedtakV2(vedtak: VedtakDVHV2): Long {
Why is there two `sendMessageForTopicVedtakV2`? This and on line 71.

2022-05-13 09:12 UTC, halvorbmundal approved these changes
LGTM

2022-05-13 10:06 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +        val response = kafkaTemplate.send(VEDTAKV2_TOPIC, vedtakV2.funksjonellId!!, vedtakV2).get()
Wrong template. The topic is on Aiven, so use kafkaAivenTemplate

2022-05-13 10:08 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +        private const val VEDTAKV2_TOPIC = "aapen-barnetrygd-vedtak-v2"
the name is teamfamilie.aapen-barnetrygd-vedtak-v2

2022-05-13 10:13 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakV2Task.kt
> +            LOG.info("Send VedtakV2 to Kafka Aiven for DVH skipped in prod")
maybe add behandlingId to logmessage, or it is difficult to debug

2022-05-13 10:14 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakV2Task.kt
> +            val vedtakV2DVH = stønadsstatistikkService.hentVedtakV2(task.payload.toLong())
I see no reason that you cannot run hentVedtakV2 in prod. As long as you toggle out sendMessage part

2022-05-13 10:20 UTC, stigebil requested changes
It would be nice if you also add a method to StønadsstatistikkController for getting VedtakDVH2. SImilar to the 
PostMapping(path = ["/vedtak"])

(and also correct the obvious copy paste error on that method. I managed to give it the n ame hentBehandlingDvh once, when it should had been named hentVedtakDvh :)

2022-05-13 11:42 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +        val response = kafkaTemplate.send(VEDTAKV2_TOPIC, vedtakV2.funksjonellId!!, vedtakV2).get()
Correct! Fixed

2022-05-13 11:42 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +        private const val VEDTAKV2_TOPIC = "aapen-barnetrygd-vedtak-v2"
Ok, fixed

2022-05-13 11:42 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakV2Task.kt
> +            LOG.info("Send VedtakV2 to Kafka Aiven for DVH skipped in prod")
removed the env check as you suggested

2022-05-13 11:46 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/stønadsstatistikk/StønadsstatistikkController.kt
> +    fun hentBehandlingDvhV2(@RequestBody(required = true) behandlinger: List<Long>): List<VedtakDVHV2> {
hentVedtakDVH2 + rename the old one too

2022-05-13 11:50 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakV2Task.kt
> +            LOG.info("Send VedtakV2 to Kafka Aiven for DVH skipped in prod")
@MengZhuNAV Not what I suggested

2022-05-13 11:56 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakV2Task.kt
> +        task.metadata["offset"] = kafkaProducer.sendMessageForTopicVedtakV2(vedtakV2DVH).toString()
What I suggested here was to move 
val vedtakV2DVH = stønadsstatistikkService.hentVedtakV2(task.payload.toLong())

out of the if sentence. and keep the sendMessageForTopic part inside the if sentence


kafkaProducer.sendMessageForTopicVedtakV2(vedtakV2DVH).toString()

2022-05-13 12:15 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +        val response = kafkaAivenTemplate.send(VEDTAKV2_TOPIC, vedtakV2.funksjonellId!!, vedtakForDVHV2Melding).get()
You should use an objectMapper which has the .setSerializationInclusion(JsonInclude.Include.NON_NULL). This to avoid null values in json. This objectmapper will create json in {"bar":"bar","foobar":null} while we want {"bar":"bar"} for this message

In the other template, this is automatic added to the producerConfig, since it use  JsonSerializer with kafkaObjectMapper set. The onprem is set up diffferent. They use StringSerializer. So inject the kafkaObjectMapper and use this one instead

2022-05-18 08:01 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakV2Task.kt
> +        task.metadata["offset"] = kafkaProducer.sendMessageForTopicVedtakV2(vedtakV2DVH).toString()
Sorry for misunderstood. Fixed now

2022-05-18 08:02 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +        val response = kafkaAivenTemplate.send(VEDTAKV2_TOPIC, vedtakV2.funksjonellId!!, vedtakForDVHV2Melding).get()
I see. I have injected the object mapper and please have a look if it is correct

2022-05-18 08:06 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +        val response = kafkaAivenTemplate.send(VEDTAKV2_TOPIC, vedtakV2.funksjonellId!!, vedtakForDVHV2Melding).get()
There are some other message sent using default objectMapper, should we also use the kafkaObjectMapper?

2022-05-18 11:05 UTC, hensol commented on src/main/kotlin/no/nav/familie/ba/sak/statistikk/producer/KafkaProducer.kt
> +        val response = kafkaAivenTemplate.send(VEDTAKV2_TOPIC, vedtakV2.funksjonellId!!, vedtakForDVHV2Melding).get()
vi kan bruke kafkaObjectMapper for bisys, men vente litt med tilbakekreving.

Har også lagt inn litt konfigendringer i kafkaaivenconfig

2022-05-19 06:12 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/task/PubliserVedtakV2Task.kt
> +            LOG.info("Hopper over å sende VedtakV2 til DVH i prod, behandling id ${vedtakV2DVH.behandlingsId}")
Burde vi hatt securelog på meldingen i begynnelsen?

2022-05-19 06:13 UTC, stigebil approved these changes

2022-05-23 07:24 UTC, merged