Valider migreringsdato også når tidligere migreringsdato ikke er lagret ned
navikt/familie-ba-sak pull request #2826
Opened 2022-09-09 12:57 UTC by idaame

### 💰 Hva skal gjøres, og hvorfor?
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-9556

Lagring av migreringsdato ble innført i midten av februar, og migreringer som skjedde før den tid ble opprettet uten å ha lagret ned migreringsdato. Hvis en saksbehandler nå skal opprette en endre migreringsdato behandling på disse sakene så er det ingen validering som sjekker at den nye datoen er senere enn eksisterende dato. Det er dette jeg prøver å løse i denne PRen.

Jeg legger til validering som kaster en feil hvis tidligere migreringsdato ikke er lagret ned, og den nye migreringsdatoen er februar 22 eller senere.  

### 🔎️ Er det noe spesielt du ønsker tilbakemelding om?
Liker ikke helt å ha en hardkodet verdi (feb 22) i koden, men må nesten det i dette tilfellet? 🤷 

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [x] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [ ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

_Jeg har ikke skrevet tester fordi:_
Føler ikke det gir nok verdi

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [x] Nei

2022-09-09 12:58 UTC, idaame commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
> +        val nyMigreringsdatoErSenereEnnMuligMigreringdatoNårForrigeMigreringsdatoIkkeErLagretNed =
Tar veldig (!!) gjerne i mot forslag til kortere navn her 😆 dette var det eneste jeg kom på akkurat nå som reflekterte innholdet

2022-09-12 05:26 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
> +                YearMonth.of(2022, 2)
For å unngå hardkodinga er det mogleg å setje denne i application.yaml, yyyy-mm-dd, og så injisere den som ein LocalDate som du så kan bruke toYearMonth() på

2022-09-12 05:28 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
> +        val nyMigreringsdatoErSenereEnnMuligMigreringdatoNårForrigeMigreringsdatoIkkeErLagretNed =
Synes det her er eit presist og fint namn, eg. At det er såpass spesifikt indikerer kanskje mest at det er eit litt spesielt høve.

2022-09-12 05:33 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
> -        if (behandling.erManuellMigreringForEndreMigreringsdato() &&
Utanfor scope for denne endringa, men eg trur vi med fordel kunne laga ein eigen `MigreringService` og flytta både denne endra metoden, hentMigreringsdato-metodane og slett-metoden dit - BehandlingService har i overkant mange ansvarsområde no.

2022-09-12 05:34 UTC, madsop-nav commented
Ser det er eit par feilande testar:

`Error:  Failures: 
Error:    LagreMigreringsdatoTest.Lagre tidligere migreringstidspunkt skal ikke kaste feil dersom forrige behandling ikke er migreringsbehandling:810 Unexpected exception thrown: no.nav.familie.ba.sak.common.FunksjonellFeil: Migreringsdatoen du har lagt inn er lik eller senere enn eksisterende migreringsdato. Du må velge en tidligere migreringsdato for å fortsette.
Error:  Errors: 
Error:    StegServiceTest.skal kjøre gjennom steg for migreringsbehandling med årsak endre migreringsdato:324 » FunksjonellFeil Migreringsdatoen du har lagt inn er lik eller senere enn eksisterende migreringsdato. Du må velge en tidligere migreringsdato for å fortsette.`

2022-09-12 05:35 UTC, madsop-nav requested changes
Synes det er ei eksplisitt og fin feilretting som bør løyse problemet.

Nokre tekniske kommentarar/innspel og eit par feilande testar, så får bli request changes i første omgang.

2022-09-12 07:28 UTC, kristeine commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
> +                YearMonth.of(2022, 2)
Tenker også at denne kunne være nice å ha som en navngitt verdi et sted, i stedet for hardkodet på denne linjen

2022-09-12 08:29 UTC, idaame commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingService.kt
> -        if (behandling.erManuellMigreringForEndreMigreringsdato() &&
Enig!! Men det får bli en annen dag 😆

2022-09-12 10:46 UTC, idaame commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/LagreMigreringsdatoTest.kt
> -    }
Sletter denne testen fordi den ikke tester noe som gir mening - hva slags type behandling forrige behandling er har egentlig ingen betydning. Det viktigste er om det ligger en migreringsbehandling i bunnen. Scenariet som er skissert opp i denne testen gir ikke helt mening: først en vanlig førstegangsbehandling, og dermed en endre migreringsdato behandling. Det skal ikke være mulig å opprette en endre migreringsdato behandling hvis det ikke er en migrering i bunnen, og denne testen er derfor unødvendig.

2022-09-12 11:27 UTC, idaame commented
Ble enig med Eivind om å droppe denne valideringen likevel, da vi har funnet ut at det er en edge case hvor dette vil bli litt feil (skal være lov til å opprette endre migreringsdato behandling på en førstegangsbehandling, og her gjelder ikke 14. februar bla.). I tillegg er det genererer man en forrigeMigreringsdato fra forrige behandling sin vilkårsvurdering hvis det ikke er lagret ned en migreringsdato. Er veldig få caser denne valideringen plukker opp, så da konkluderte vi med å droppe den.

2022-09-12 11:27 UTC, closed without merging