Ikke send autobrev hvis ytelsen har gått ut for barnet som er 6 eller 18
navikt/familie-ba-sak pull request #2950
Opened 2022-10-13 12:57 UTC by stigebil

### 💰 Hva skal gjøres, og hvorfor?
Brev om omregning 18 år skal ikke automatisk sendes i saker det ikke er løpende ytelse for barnet. Fikser tilsvarende sak for omregning 6 år

### 🔎️ Er det noe spesielt du ønsker tilbakemelding om?
_Er det noe du er usikker på eller ønsker å diskutere? Beskriv det gjerne her eller kommenter koden det gjelder._

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [ ] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [ ] Jeg har config- eller sql-endringer. I så fall, husk manuell deploy til miljø for å verifisere endringene.
- [x] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

_Jeg har ikke skrevet tester fordi:_

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [ ] Nei

2022-10-14 09:49 UTC, madsop-nav commented
Error:  Failures: 
Error:    Autobrev6og18ÅrFortsattOpphørtTest.Skal støtte fortsatt opphørt som resultat:166 expected: <2> but was: <1>
Error:    TriggingAvAutobrev6og18ÅrTest.Omregning og autobrev skal kjøres for 18 år og ikke 6 år:42->kjørFørstegangsbehandlingOgTriggAutobrev:211 expected: <2> but was: <1>

2022-10-14 09:53 UTC, madsop-nav requested changes
Utover dei feilande testane ser det fornuftig og fint ut.

2022-10-17 08:52 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt
> +            it.stønadTom.plusMonths(1) == årMåned || it.stønadTom.plusMonths(1).isAfter(årMåned)
Blir det riktig å ha med `it.stønadTom.plusMonths(1) == årMåned` her? Dette mener jeg kan leses som `opphørFom == inneværendeMåned`, og dermed `harLøpendeYtelse = false`

2022-10-17 10:19 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt
> +            it.stønadTom.plusMonths(1) == årMåned || it.stønadTom.plusMonths(1).isAfter(årMåned)
Er litt usikker selv. Skrev den originalt uten plusMonths, men da feilet den andre testene som 
Omregning og autobrev skal kjøres for 6 år og ikke 18 år i TriggingAvAutobrev6og18ÅrTest
For 18 år caset så ser aty
AndelTilkjentYtelse(id = 2000005, behandling = 999951, type = ORDINÆR_BARNETRYGD, prosent = 100,beløp = 1054, stønadFom = 2022-09, stønadTom = 2022-09, periodeOffset = 4, forrigePeriodeOffset = null, kildeBehandlingId = 999951, nasjonaltPeriodebeløp = 1054, differanseberegnetBeløp = null)

2022-10-17 10:19 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt
> +            it.stønadTom.plusMonths(1) == årMåned || it.stønadTom.plusMonths(1).isAfter(årMåned)
@idaame Hva mener du om dette?

2022-10-17 13:18 UTC, idaame commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt
> +            it.stønadTom.plusMonths(1) == årMåned || it.stønadTom.plusMonths(1).isAfter(årMåned)
Jeg trooor dette blir riktig:
Hvis alder=18, så må vi sjekke at barnet som fylte 18 hadde løpende ytelse i forrige måned (og ikke denne), og hvis alder=6 så må vi sjekke at barnet som fyller 6 har løpende ytelse både forrige og inneværende måned. 

Så jeg tenker egentlig at det du har skrevet gir mening, spørsmålet er bare om vi syns det er eksplisitt nok 🤷

2022-10-18 11:23 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrService.kt
> +            it.stønadTom.plusMonths(1) == årMåned || it.stønadTom.plusMonths(1).isAfter(årMåned)
@tnarland @idaame PR oppdatert

2022-10-19 10:49 UTC, idaame commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt
> +            tilfeldigPerson(LocalDate.now().minusYears(Alder.SEKS.år.toLong()).minusMonths(1))
Skal denne egentlig ha minus 18 år?

2022-10-19 10:50 UTC, idaame commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt
> +            tilfeldigPerson(LocalDate.now().minusYears(Alder.SEKS.år.toLong()).minusMonths(1))
Skal denne variabelen hete barn6årUtenAktivTilkjentYtelse?

2022-10-19 11:03 UTC, stigebil commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt
> +            tilfeldigPerson(LocalDate.now().minusYears(Alder.SEKS.år.toLong()).minusMonths(1))
@idaame fikset

2022-10-19 11:12 UTC, idaame commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt
> +    }
Når jeg tenker meg om, burde ikke denne testen egentlig feile sånn den er satt opp nå? Personen som blir 18 har en andel tilkjent ytelse med tom satt til forrige måned, og det er jo det den nye koden egentlig skal gi tommel opp på? 🤔

2022-10-19 14:06 UTC, stigebil commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/autovedtak/omregning/Autobrev6og18ÅrServiceTest.kt
> +    }
Den gikk igjennom fordi det var et annet barn i overskriving av mock for aty, dermed hadde den ingen løpende ytelse. Skrevet om litt og bruker samme barn overalt

2022-10-20 06:57 UTC, merged