Teknisk/tislinje fra tidspunkt og forbedrede map funksjoner
navikt/familie-ba-sak pull request #2979
Opened 2022-10-23 07:41 UTC by nav-jorn-ola-birkeland

### 💰 Hva skal gjøres, og hvorfor?
`TidslinjeSomStykkerOppTiden` vil kunne introdusere flere/lengre perioder med null-verdier enn underliggende tidslinje har. Det er unødvendig og forvirrende. Legger til `tidslinjeFraTidspunkt` som løser problemet og gir en mer funksjonell implementasjon. 

Det bør lages et par PRer til etter denne:
* Endre navn på `map` til `mappInnhold` og `mapIkkeNull` til `mapInnholdIkkeNull`
* Fjerne bruken av `TidslinjeSomStykkerOppTiden` og erstatte med `tidslinjeFraTidspunkt`

### 🔎️ Er det noe spesielt du ønsker tilbakemelding om?
Nei. 

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [ ] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [ ] Jeg har config- eller sql-endringer. I så fall, husk manuell deploy til miljø for å verifisere endringene.
- [x] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

_Jeg har ikke skrevet tester fordi:_

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [x] Nei

2022-10-24 08:31 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeFraTidspunkt.kt
> +    constructor(innhold: I?) : this(innhold, true)
Synes denne bør ta inn `I`, alternativt bør vi ha logikk her som flippar `harInnhold`-flagget avhengig av om `innhold` har verdi eller ikkje.

2022-10-24 08:32 UTC, idaame commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            else -> Innholdsresultat<R>(mapper(innholdsresultat.innhold))
tidslinjeFraTidspunkt filtrerer på harInnhold, noe som gjør at jeg vil tenke at man aldri vil få false her(?) Mest sannsynlig er det jeg som har misforstått noe, men tar gjerne en liten gjennomgang på koden så jeg blir tryggere på det jeg leser 😅

2022-10-24 08:32 UTC, idaame commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinjeTest.kt
> +    }
Bra med tester 🚀

2022-10-24 08:41 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeFraTidspunkt.kt
> +                sistePeriode != null && sistePeriode.kanUtvidesMed(tidspunktMedInnholdsresultat) ->
Tidslinje-DSLen byrjar å bli ganske fin og omfattande no 🤩

2022-10-24 08:41 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeFraTidspunkt.kt
> +                    perioder.replaceLast(sistePeriode.utvidMed(tidspunktMedInnholdsresultat))
Kan vi døpe om `replaceLast` til `erstattSiste`? Og for så vidt tilsvarande med `lastOrNull` over.

2022-10-24 08:48 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeFraTidspunkt.kt
> +    val periode = this.firstOrNull { it.fraOgMed <= tidspunkt && it.tilOgMed >= tidspunkt }
Korvidt eit tidspunkt er i ein periode slår meg som noko vi kan ha ein eigen metode for, sånn at denne kunne vorte noko a la `this.firstOrNull { it.omfatter(tidspunkt) }`

2022-10-24 08:54 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            else -> Innholdsresultat<R>(mapper(innholdsresultat.innhold))
Samtidig kan `innholdsresultatForTidspunkt` returnere `Innholdsresultat.utenInnhold()` viss tidspunktet er utanfor perioden, så teknisk sett gir det meining å ta høgde for false her. Men det høyrast jo ut som ein rar situasjon.

2022-10-24 08:57 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            else -> Innholdsresultat<R>(mapper(innholdsresultat.innhold))
Okei, når eg ser litt nærmare på det: desse linjene (15-20) blir sendt inn som det som i `tidslinjeFraTidspunkt` blir `tidspunktMapper`, som blir kalt _før_ filtreringa på `harInnhold`. Så det er på sett og viss denne som gjer at `harInnhold`-filteret i tidslinjeFraTidspunkt blir riktig.

2022-10-24 08:58 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            innholdsresultat.innhold == null -> Innholdsresultat.utenInnhold()
Her klager min IntelliJ på at `innholdsresultat.innhold == null` bør vera i parentesar, og at det blir ein feil i 1.8

2022-10-24 08:59 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            innholdsresultat.innhold == null -> Innholdsresultat.utenInnhold()
Kan eventuelt slå saman false og null-høva her, til omtrent 
`false, (innholdsresultat.innhold == null) -> Innholdsresultat.utenInnhold()`

2022-10-24 09:01 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            innholdsresultat.innhold == null -> Innholdsresultat.utenInnhold()
Men vent litt, konseptet med at innhold skal kunne vera null når harInnhold er true skurrar veldig for meg. Der trur eg `Innholdsresultat` bør vera strengare på at det ikkje skal kunne vera mogleg.

(På sett og vis samme kommentar som min første om at innhold bør vera I, ikkje I?)

2022-10-24 09:04 UTC, madsop-nav commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinjeTest.kt
> +        assertEquals(mai(2022), faktisk.tilOgMed())
Kanskje også asserte noko her for tidspunkta inni her som ikkje har ein periode, feks september 2020->feb 2021?

2022-10-24 09:05 UTC, madsop-nav requested changes
Verkar lovande og som eit godt steg i rett retning, men nokre ting skurrar litt (sjå kommentarar)

2022-10-24 16:16 UTC, nav-jorn-ola-birkeland commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeFraTidspunkt.kt
> +    constructor(innhold: I?) : this(innhold, true)
Enig!

2022-10-24 20:50 UTC, nav-jorn-ola-birkeland commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            else -> Innholdsresultat<R>(mapper(innholdsresultat.innhold))
Stemmer, tror jeg. Det er to tilfeller som er uten innhold:
* Retur-verdien fra mapper-funksjonen kan være uten innhold. Det er den `tidslinjeFraTidspunkt` kikker på
* `innholdsresultatForTidspunkt` mot en tidslinje, kan gi `utenInnhold`. Det skjer når tidspunktet det spørres etter ligger utenfor tidslinja, eller det er et "hull" i tidslinja.

2022-10-24 21:03 UTC, nav-jorn-ola-birkeland commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            innholdsresultat.innhold == null -> Innholdsresultat.utenInnhold()
Litt av hensikten med utvidelsen (som ikke har kommet klart frem) er å få et skille mellom null som innhold og der innhold helt mangler. Frem til nå har null blitt brukt til å representere begge deler. Så nå kan innholdet ha tre tilstander:
* innhold mangler
* innhold finnes, men er null
* innhold finnes, og har en verdi (forskjellig fra null)

Internt i `innholdsresultat` spiller ikke  verdien på innhold noen rolle hvis `harInnhold` er `false`. Men bruker null fordi det er enklest

2022-10-24 21:08 UTC, nav-jorn-ola-birkeland commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/komposisjon/TidslinjeFraTidspunkt.kt
> +    constructor(innhold: I?) : this(innhold, true)
Endringen som innføres (som ikke er beskrevet), innfører et skille mellom innhold og ikke-innhold. Innhold _kan_ også være null. Derfor tillates null her.

2022-10-25 08:23 UTC, nav-jorn-ola-birkeland commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinjeTest.kt
> +        assertEquals(mai(2022), faktisk.tilOgMed())
Enig!

2022-10-27 12:21 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/tidslinje/transformasjon/MapTidslinje.kt
> +            innholdsresultat.innhold == null -> Innholdsresultat.utenInnhold()
Ah, riktig. Det var ikkje opplagt for meg at det skiljet er bevisst.

Eg trur eg vil føretrekkje at `harInnhold` ikkje er ein boolean, men heller ein enum. Det vil synleggjera at det er snakk om nettopp tre forskjellige tilstandar.

2022-11-07 11:18 UTC, idaame approved these changes
✨

2022-11-07 12:24 UTC, madsop-nav approved these changes

2022-11-07 13:05 UTC, merged