Det ser ut som feilen oppstår når vi har ei nullutbetaling no, men de…
navikt/familie-ba-sak pull request #3046
Opened 2022-11-11 14:57 UTC by madsop-nav

…r vi i ei tidlegare behandling har (med rette, etter alt å dømme) betalt ut. I dei eksempla eg har sett har det vore forelder og barn som har budd nokre månadar i Noreg før dei flytta til utlandet.

I den første behandlinga har vi da sendt til oppdrag, og vi har nokre andel tilkjent ytelse der med positiv sum. Så har saksbehandlar anten oppheva denne behandlinga, eller gjort ei revurdering. I den nye behandlinga som kjem blir resultatet for alt nytt nullutbetaling, altså blir ingenting derifrå sendt til oppdrag.

Derimot "flyttar vi over" andel tilkjent ytelse frå den første behandlinga, og gir desse den nye behandlings-iden. Som følge av det finn logikken vår desse når vi sjekkar korvidt vi har andelar som skal føre til utbetaling, og dermed prøver vi å hente status frå oppdrag. Men no spør vi jo mot oppdrag for den nye behandlings-iden, som det ikkje er sendt noko på - desse andelane vart jo sendt på den gamle behandlinga. Dermed finn ikkje oppdrag noko, og dermed får vi feil.

Denne committen er ein naiv første-versjon-fiks på problemet. Bør få gjenskapt det også i ein test, men det nærmar seg raskt helg.

### 💰 Hva skal gjøres, og hvorfor?
_Skriv 1 eller 2 setninger om hvilken funksjonell endring som blir implementert. Ta med en **lenke til Favro** og
skriv en kort beskrivelse av hvorfor endringen skal gjøres._

### 🔎️ Er det noe spesielt du ønsker tilbakemelding om?
_Er det noe du er usikker på eller ønsker å diskutere? Beskriv det gjerne her eller kommenter koden det gjelder._

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [ ] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [ ] Jeg har config- eller sql-endringer. I så fall, husk manuell deploy til miljø for å verifisere endringene.
- [ ] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

_Jeg har ikke skrevet tester fordi:_

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [ ] Nei

2022-11-14 09:40 UTC, nav-jorn-ola-birkeland requested changes
Jeg tror den riktige fiksen er å sjekke `utbetalingsoppdrag` på `TilkjentYtelse` knyttet til behandlingen. Hvis det mangler `utbetalingsperiode`(r), så har vi ikke sendt noe til Oppdrag, og vi skal heller ikke sjekkes status, dvs kan sende `OppdrragStatus.KVITTERT_OK` umiddelbart.

erAndelSomSkalSendesTilOppdrag=false kan bety at _denne_ behandlingen har fjernet andelen, men den fantes en på forrige. Da vil utbetalingsoppdraget ha et _opphør_, og ikke være tomt. Det er blitt sendt til oppdrag, og status må sjekkes

2022-11-14 10:02 UTC, madsop-nav commented
> `erAndelSomSkalSendesTilOppdrag=false` kan bety at _denne_ behandlingen har fjernet andelen, men den fantes en på forrige. Da vil utbetalingsoppdraget ha en utbetalingsperiode som er _opphør_, og ikke være tomt. Det er blitt sendt til oppdrag, og status må sjekkes.

Aha. Da har vi (enda ein) feil i eksisterande kode der.

2022-11-14 14:23 UTC, nav-jorn-ola-birkeland requested changes

2022-11-14 14:23 UTC, nav-jorn-ola-birkeland commented on src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt
> +        if (tilkjentYtelse.utbetalingsperioder().isEmpty() || andelerTilkjentYtelse.isEmpty()) {
Jeg _tror_ også denne er litt feil. Vi risikerer det samme her; ny behandling kommer frem til at tilkjent ytelse faller bort, dvs at det ikke er noen andeler. Utbetalingsoppdraget vil da inneholde én ellere flere perioder med opphør. Da   har vi sendt oppdraget, og vi må sjekke status. 

Jeg _tror_ det riktigste er å sjekke utbetalingsoppdraget, og _bare_ utbetalingsoppdraget.

2022-11-14 14:30 UTC, nav-jorn-ola-birkeland commented on src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt
> +    fun hentStatus(oppdragId: OppdragId, behandlingId: Long, tilkjentYtelse: TilkjentYtelse): OppdragStatus {
Kunne ikke denne hentet TilkjentYtelse fra behandlingId, i stedet for å sende inn? (Har ikke oversikt over om TilkjentYtelse allerede var hentet ut "på utsiden", og derfor var lett tilgjengelig)

2022-11-14 14:35 UTC, madsop-nav commented on src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/økonomi/ØkonomiService.kt
> +        if (tilkjentYtelse.utbetalingsperioder().isEmpty() || andelerTilkjentYtelse.isEmpty()) {
Fair enough.

Spørsmålet er da kva vi gjer i dei tilfella kor andelerTilkjentYtelse _er_ tom her, men utbetalingsperioder ikkje er tom. Det skjer iallfall i test (`Error:    TekniskEndringAvFødselshendelseTest.Skal teknisk opphøre fødselshendelse:167 » NoSuchElement List is empty.`), litt usikker på om det også skjer i prod-kode.

2022-11-19 11:49 UTC, nav-jorn-ola-birkeland approved these changes

2022-11-21 11:02 UTC, merged