Nav 11431 fortrolig barn uten manuelle brevmottakere
navikt/familie-ba-sak pull request #3696
Opened 2023-06-09 09:28 UTC by marius-nav

### 💰 Hva skal gjøres, og hvorfor?
_Skriv 1 eller 2 setninger om hvilken funksjonell endring som blir implementert. Ta med en **lenke til Favro** og
skriv en kort beskrivelse av hvorfor endringen skal gjøres._

https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-11431

Nytt endepunkt for validering av fortrolig adressebeskyttelse (STRENGT_FORTROLIG / STRENGT_FORTROLIG_UTLAND)
Mottar array av personidenter og returnerer de som PDL anser å ha fortrolig adressebeskyttelse)

### 🔎️ Er det noe spesielt du ønsker tilbakemelding om?
_Er det noe du er usikker på eller ønsker å diskutere? Beskriv det gjerne her eller kommenter koden det gjelder._
Bør det lages separate tester for dette endepunktet - eller er det tilstrekkelig med testen som tester endepunkt mot PDL allerede?

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [X] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [X] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇
- Usikker om det er nødvendig for hvert enkelt endepunkt mot PDL (som nevnt over..)?

_Jeg har ikke skrevet tester fordi:_
Jobber hovedsakelig i frontend og fått hjelp til å lage nødvendig back-end kode..

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [X] Nei

2023-06-09 10:31 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt
> +    @PostMapping(path = ["/personidenterMedStrengtFortroligGradering"])
Er det kanskje mulig å bruke dataen som finnes i personinformasjon (dataen som hentes fra /person) i frontend, så trenge rman ikke gjøre dette kallet?

2023-06-13 06:49 UTC, stigebil commented
For å fikse ktlint:
`mvn antrun:run@ktlint-format`

2023-06-13 06:50 UTC, stigebil commented
Må fikse kompileringsfeil

2023-06-14 07:48 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt
> +    @PostMapping(path = ["/personidenterMedStrengtFortroligGradering"])
Dataene i personinformasjon er i dag ikke tilstrekkelig for å kunne validere "on-the-fly" om noen er fortrolige.
Det kan per dags dato legges til personer som ikke inngår i disse "lokale person dataene" - som da ikke vil valideres.
Med det ny endepunktet vil personene kunne valideres "on-the-fly" også ved gjenopptakelse av saken mm. (hver gang steget resubmittes - i motsetning til i dag)

2023-06-14 17:28 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt
> +    @PostMapping(path = ["/personidenterMedStrengtFortroligGradering"])
Er forsåvidt data nylig hentet fra PDL det som finnes i personinformasjon også. Så hadde det ikke vært for at løsningen lar oss legge til barn som ikke er i relasjon med søker iht. PDL, tror jeg vi kunne klart oss med de, ja

2023-06-15 06:30 UTC, tnarland approved these changes

2023-06-19 09:42 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt
> +    @PostMapping(path = ["/personidenterMedStrengtFortroligGradering"])
Vet ikke helt om jeg skjønte dette. Hva mener dere? 

(I tillegg burde kanskje url'en være `hyphen-case`?)

2023-06-19 09:57 UTC, blommish requested changes
Skjønner fortsatt ikke hvorfor man trenger denne endepunkten, burde kunne håndteres på en annen måte. 
For meg virker det som at det skaper en flyt som er unødvendig kompleks

2023-06-27 12:55 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingValideringService.kt
> +            throw FunksjonellFeil(melding, frontendFeilmelding)
Tenker man kan ha exit-early hvis mulig. Dvs hvis det ikke finnes noen brevmottakere, så trenge rman ikke å gjøre noe videre, samme sak med 
```suggestion
        val brevmottakere = brevmottakerService.hentBrevmottakere(behandlingId).takeIf { it.isNotEmpty() } ?: return
        val personopplysningGrunnlag = persongrunnlagService.hentAktivThrows(behandlingId = behandlingId)
        val personIdentList = personopplysningGrunnlag.søkerOgBarn
            .takeIf { it.isNotEmpty() }
            ?.map { it.aktør.aktivFødselsnummer() }
            ?: return
        val strengtFortroligePersoner =
            familieIntegrasjonerTilgangskontrollService.returnerPersonerMedAdressebeskyttelse(personIdentList)

        if (strengtFortroligePersoner.isNotEmpty()) {
            val melding =
                "Behandlingen (id: $behandlingId) inneholder ${strengtFortroligePersoner.size} person(er) med strengt fortrolig adressebeskyttelse og kan ikke kombineres med manuelle brevmottakere (${brevmottakere.size} stk)."
            val frontendFeilmelding =
                "Behandlingen inneholder personer med strengt fortrolig adressebeskyttelse og kan ikke kombineres med manuelle brevmottakere."
            throw FunksjonellFeil(melding, frontendFeilmelding)
        }
```

2023-06-27 12:55 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/FamilieIntegrasjonerTilgangskontrollService.kt
> +    fun returnerPersonerMedAdressebeskyttelse(personIdentList: List<String>): List<String> {
Burde denne hete noe annet enn `returner` ?
Kanskje også noe med `strengt fortrolig`, eks `identerMedStrengtFortrolig`? 

`personIdentList` -> `personIdenter`

2023-06-27 12:55 UTC, blommish commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingValideringService.kt
> +class BehandlingValideringService(
`BehandlingValidering` blir veldig overordnet her, det finnes sikkert en del validering rundt om
Kanskje `ValiderBrevmottakerService`?

2023-06-28 05:29 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingValideringService.kt
> +            throw FunksjonellFeil(melding, frontendFeilmelding)
Ok

2023-06-28 05:30 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingValideringService.kt
> +class BehandlingValideringService(
ok

2023-06-28 05:35 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/familieintegrasjoner/FamilieIntegrasjonerTilgangskontrollService.kt
> +    fun returnerPersonerMedAdressebeskyttelse(personIdentList: List<String>): List<String> {
Ok

2023-06-28 06:09 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/grunnlag/personopplysninger/PersonController.kt
> +    @PostMapping(path = ["/personidenterMedStrengtFortroligGradering"])
Validering flyttet til backend så dette endepuunktet er ikke lenger relevant

2023-06-28 11:03 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingValideringService.kt
> +    fun validerAtBehandlingIkkeInneholderStrengtFortroligePersonerMedManuelleBrevmottakere(behandlingId: Long) {
Ok

2023-06-28 11:15 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingValideringService.kt
> +    fun validerAtBehandlingIkkeInneholderStrengtFortroligePersonerMedManuelleBrevmottakere(behandlingId: Long) {
Ok

2023-06-28 11:16 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/SystemOnlyPdlRestClient.kt
> +        return feilsjekkOgReturnerData(
Utgår - endepunkt fjernet - validering nå i backend

2023-06-29 10:58 UTC, halvorbmundal commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/ValiderBrevmottakerService.kt
> +        val brevmottakere = brevmottakerService.hentBrevmottakere(behandlingId).takeIf { it.isNotEmpty() } ?: return
Burde vi sjekke om `brevmottakere` og `personIdenter` intersecter? Hvis ikke, trenger vi da denne linja?

2023-07-04 07:17 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/kjerne/behandling/BehandlingStegController.kt
> +        behandlingValideringService.validerAtBehandlingIkkeInneholderStrengtFortroligePersonerMedManuelleBrevmottakere(behandlingId = behandling.id)
Fått feed-back fra Stig og Halvor. Denne er flyttet til preValiderSteg.

2023-07-04 08:30 UTC, marius-nav commented on src/main/kotlin/no/nav/familie/ba/sak/integrasjoner/pdl/SystemOnlyPdlRestClient.kt
> +    @Cacheable("adressebeskyttelsebolk", cacheManager = "shortCache")
Enig med Johan at dette kan gjøres i separat PR siden.

2023-07-06 06:08 UTC, hensol approved these changes
Jeg synes dette ser bra ut. Veldig bra du koder litt kotlin også 👍 

Har kun kommentert noe småpirk.

2023-07-06 06:08 UTC, hensol commented on src/test/enhetstester/kotlin/no/nav/familie/ba/sak/kjerne/behandling/ValiderBrevmottakerServiceTest.kt
> +    fun `Skal validere at er ok når ikke inneholder noen strengt fortrolige personer og inneholder en brevmottaker`() {
kanskje endre til "Skal ikke kaste funksjonell feil når behandling ikke inneholder noen strengt fortrolige personer og inneholder minst en manuell brevmottaker"

2023-07-06 08:11 UTC, merged