Feature/først utfall metrikk
navikt/familie-ba-sak pull request #457
Opened 2020-09-16 14:07 UTC by MengZhuNAV

test metrics

2020-09-18 08:21 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingMetrics.kt
> +            return counterMap.plus(Pair(vilkårNøkkel(spesifikasjon.identifikator, personType, resultat, behandlingOpprinnelse),
Instead of changing the behavious of this function we could rollback and just add the new første utfallmetrikkel here.

2020-09-18 08:25 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/EvaluerFiltreringsreglerForFødselshendelse.kt
> +            LOG.info("increase first fail counter ${evaluering.identifikator} ${filtreringsreglerFørsteUtfallMetrics[evaluering.identifikator]}")
remove log-statement

2020-09-18 08:25 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/EvaluerFiltreringsreglerForFødselshendelse.kt
> +            LOG.info("increase counter ${evaluering.identifikator + evaluering.resultat.name}")
remove

2020-09-18 08:26 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingMetrics.kt
> +    var vilkårsvurderingFørstUtfall = mapOf<String, Counter>()
shoudl be mutablemap.

2020-09-18 08:26 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingMetrics.kt
> +                            vilkårsvurderingFørstUtfall = LeggTilEntryTilMetrikkMap(vilkårsvurderingFørstUtfall,
remove vilkårsvurderingUtfall and vilkårsvurderingFørstUtfall

2020-09-21 08:01 UTC, henninghaakonsen requested changes
Litt uoversiktlig, så fint om dere får ryddet opp litt. Mer eksplisitte metoder og skille funksjonalitet er bedre i dette tilfelle tenker jeg.

2020-09-21 08:46 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/EvaluerFiltreringsreglerForFødselshendelse.kt
> +                førsteutfall= økTellereForFørsteUtfall(it, førsteutfall)
The counter should not be null, otherwise it is a bug. We use !! because we want to get an exception when something wrong.

2020-09-21 08:48 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    }
The method is used to check if a vilkår such as "Mor bosatt i riket" has failed. Can you suggest a better name for it?

2020-09-21 08:51 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +        )
The order defined in vilkår.kt does not distinguish the person type. For example, there is one vilkår corresponding to both "mor bosatt i riket" and "barn bosatt i riket". However the functional people defined these two vilkår with different priority.

2020-09-21 08:54 UTC, MengZhuNAV commented on src/test/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseIntegrasjonTest.kt
> +        økTellerForFørsteUtfallVilkårVedAutomatiskSaksbehandling(any(), any())} returns Unit
Fixed. Thank you for letting me know this

2020-09-21 11:00 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +        )
Right, but you could just add a simple check instead of defining the order two times. Anyhow, the order is the same for "søker" and "barn", it is just that "søker" has two instead of five "vilkår.

2020-09-21 11:01 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/EvaluerFiltreringsreglerForFødselshendelse.kt
> +                førsteutfall= økTellereForFørsteUtfall(it, førsteutfall)
Right, but this will create a NPE and will look bad. You could "catch" it with ?: for instance.

2020-09-21 11:02 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    }
What about `erVilkårForPersonNei`?

2020-09-21 11:09 UTC, oyvindhagen approved these changes
Ser bra ut. Et par kommentarer.

2020-09-21 11:09 UTC, oyvindhagen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +        )
Enig med Henning i at det er litt uheldig å ha rekkefølgen definert flere steder. Kunne man ha bygget opp denne listen ved å hente ut vilkårene for søker og deretter barn (med den rekkefølgen de er definert i i vilkår.kt)? På den måten definerer man her kun at søkers vilkår skal sees på før barnas.

2020-09-21 11:09 UTC, oyvindhagen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingMetrics.kt
> +                            vilkårsvurderingFørstUtfall = LeggTilEntryTilMetrikkMap(vilkårsvurderingFørstUtfall,
Mangler en e her og et par andre steder for konsekvent navngivning andre steder. Pirk :)
vilkårsvurderingFørst**e**Utfall

2020-09-22 08:54 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/EvaluerFiltreringsreglerForFødselshendelse.kt
> +                førsteutfall= økTellereForFørsteUtfall(it, førsteutfall)
... When we use !! we tell the compiler that we have control of this and we know that it can't be null ... I prefer !! I think ?: is wrong but it's ok for me to change it if you are not convinced ..

2020-09-22 08:59 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +        )
I can do this but I do not quite agree, because:
1)  I prefer explicit order instead of order based on the enum declaration. The latter is difficult to understand; and may cause maintenance problems.
2) As @henninghaakonsen said we have to add a simple check here if we use the enum order, then the logic is still defined in two places (the check is still part of the logic). This is even worse than "duplicated" logic, because the logic is distributed and change on any of the two place can break the logic.

The idea of the current implementation is to decouple the vilkår order from the enum declaration, therefore they can change independently of each other.

2020-09-22 09:02 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +        )
But why can't we just move it to the enum? Like, get `fun hentRekkefølge` or something like that?

2020-09-22 09:03 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/EvaluerFiltreringsreglerForFødselshendelse.kt
> +                førsteutfall= økTellereForFørsteUtfall(it, førsteutfall)
Ok, not a big problem :)

2020-09-22 09:04 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    }
Agree with both of you👍

2020-09-22 09:10 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårsvurderingMetrics.kt
> +                            vilkårsvurderingFørstUtfall = LeggTilEntryTilMetrikkMap(vilkårsvurderingFørstUtfall,
Yes, thank you!

2020-09-22 09:12 UTC, MengZhuNAV commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +        )
Yes we can do that, and it sounds better than current solution👍

2020-09-22 09:13 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +        )
... I agree that we should use Vilkår-enum and remove the enum we introduced ...

2020-09-22 09:29 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    }
... Ok, bra forslag Øyvind, kanskje vi skal prøve og gjøre det ytterligere mer lesbart? ...

2020-09-22 10:30 UTC, henninghaakonsen approved these changes

2020-09-22 22:40 UTC, merged