Andre fodsel tidligere enn fem dager går igjennom
navikt/familie-ba-sak pull request #516
Opened 2020-10-13 08:19 UTC by MarcusGustafson74

Automatisk vedtak feiler om tidligere barn er født mindre enn fem måneder tidligere men mer en fem dager senere.

2020-10-13 08:25 UTC, henninghaakonsen requested changes
Her snakket vi vel også om å endre på teksten til grafana/oppgave, så det må endres. Hvis du endrer på enumer som lagres må vi også ha et flyway-script.

2020-10-13 08:25 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/filtreringsregler/Regler.kt
> +        fakta.restenAvBarna.all { barnFraHendelse.fødselsdato.isAfter(it.fødselsdato.plusMonths(5)) ||
&&?

2020-10-13 08:25 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/filtreringsregler/Regler.kt
>  internal fun merEnn5mndSidenForrigeBarn(fakta: Fakta): Evaluering {
Endre navn på metode til å reflektere regel også (eventuelt legg til doc)

2020-10-14 06:37 UTC, MarcusGustafson74 commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/filtreringsregler/Regler.kt
> +        fakta.restenAvBarna.all { barnFraHendelse.fødselsdato.isAfter(it.fødselsdato.plusMonths(5)) ||
Jeg tenkte && først også, men || er faktisk riktig. Om før fem dager eller etter fem måneder så er det sant.

2020-10-14 06:42 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/filtreringsregler/Regler.kt
> +        fakta.restenAvBarna.all { barnFraHendelse.fødselsdato.isAfter(it.fødselsdato.plusMonths(5)) ||
Ja okei, jeg tenkte omvent. Altså før 5 måneder og etter 5 dager så false :P Men ja, fungerer dette også såklart 👍

2020-10-14 07:54 UTC, henninghaakonsen approved these changes

2020-10-14 12:59 UTC, merged