Vedtaksdato som LocalDateTime
navikt/familie-ba-sak pull request #562
Opened 2020-10-23 08:36 UTC by hensol

Endret vedtaksdato type fra localdate til localDateTime.

2020-10-23 08:44 UTC, henninghaakonsen requested changes
Noen kommentarer og litt skeptisk(ikke god nok kontroll) til timezone...

2020-10-23 08:44 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestVedtak.kt
> +        vedtaksdato = this.vedtaksdato?.toLocalDate(),
Jeg tror ikke det er noe problem om denne også er localdatetime til frontend.

2020-10-23 08:44 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
> +                vedtaksdato = LocalDateTime.now(TIMEZONE)
Hvorfor trenger vi tidssone på denne? Vi har det ingen andre steder i systemet og jeg kan bare tenke meg bugsene vi møter på fremover 🤯

2020-10-23 08:44 UTC, henninghaakonsen commented on src/test/kotlin/no/nav/familie/ba/sak/dokument/MalerServiceTest.kt
> +        vedtak.vedtaksdato = LocalDateTime.of(fødselsdato.year, fødselsdato.month, fødselsdato.plusDays(7).dayOfMonth, 4, 35)
Kanskje man kan gjøre noe slikt?

```
val localDateTime = fødselsdato.atStartOfDay() 
```

2020-11-10 19:59 UTC, hensol commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vedtak/VedtakService.kt
> +                vedtaksdato = LocalDateTime.now(TIMEZONE)
tidssonen håndteres vel også av baseimage når jeg tenker meg om.
`ENV TZ="Europe/Oslo"`

2020-11-10 20:33 UTC, hensol commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/restDomene/RestVedtak.kt
> +        vedtaksdato = this.vedtaksdato?.toLocalDate(),
topp da blir klokkeslett med til frontend

2020-11-11 07:18 UTC, henninghaakonsen approved these changes

2020-11-11 07:19 UTC, oyvindhagen approved these changes

2020-11-11 07:48 UTC, hensol commented
Vedtaksdato som LocalDateTime

2020-11-11 07:48 UTC, merged