Rename rollback-automatisk-regelkjoring til skal-iverksette-fodselshendelse.
navikt/familie-ba-sak pull request #614
Opened 2020-11-10 15:31 UTC by geirmundsimonsen

Dette medfører en booleansk flip, kode og tester endret for å reflektere dette.

2020-11-10 21:18 UTC, hensol requested changes
Ser bra ut dette 👍 

jeg lar meg forvirre litt av navnet på testene og hva de faktisk tester. 

Kanskje det kan forbedres?

2020-11-10 21:18 UTC, hensol commented on src/test/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseServiceTest.kt
>      fun `Skal iverksette behandling hvis filtrering og vilkårsvurdering passerer og toggle er skrudd av`() {
Mulig jeg lett lar meg forvirre, men stemmer navnet på testen overens med det som testes?

2020-11-10 21:18 UTC, hensol commented on src/test/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseServiceTest.kt
> +        if (flerlinger) barna.plus(Person(type = PersonType.BARN,
👨‍🏫  👍

2020-11-11 08:27 UTC, geirmundsimonsen commented
Fint - da mangler det å kunne sjekke dev-kontekst, da den kommer til å erstatte isPresent-logikken, som ikke holder vann. Benytter meg gjerne av foreldrepengers løsning her.

2020-11-11 08:42 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
> +            override fun isPresent(toggleId: String): Boolean {
Kunne vi like gjerne kastet en feil/gitt default verdi i isEnabled? Hva vinner vi ved å måtte kalle isPresent også isEnabled?

2020-11-12 15:16 UTC, geirmundsimonsen commented on src/main/kotlin/no/nav/familie/ba/sak/config/FeatureToggleConfig.kt
> +            override fun isPresent(toggleId: String): Boolean {
måtte forkaste isPresent, se kommentar ovenfor.

Har pushet ny løsning, som bruker cluster (NAIS_CLUSTER_NAME) for å avgjøre hvorvidt vi kjører i prod.

2020-11-12 15:48 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    private fun fødselshendelseSkalRullesTilbake(): Boolean {
Denne logikken bør flyttes til en util-funksjon som tar inn verdien til togglen. I tillegg så bør også metodenavnet og logikken til ba-sak endres slik at vi også slipper gjennom dersom denne er true. Nå endrer vi vel bare togglen og negerer svaret for at det skal passe i løypa til ba-sak igjen?

2020-11-16 10:07 UTC, geirmundsimonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    private fun fødselshendelseSkalRullesTilbake(): Boolean {
Vi kan godt flytte denne funksjonen til utility, den vil kreve to parametre: toggle-verdien og hvilket cluster vi er i.

Tenker du at vi endrer funksjonen fra "fødselshendelseSkalRullesTilbake" til å være en "skalIverksetteFødselshendelse"-funksjon? Det burde isåfall ikke være noe problem.

Husk at siden semantikken er endret, trenger vi å ta med hvilket cluster vi er i. Ønsket var å lage en "ordentlig" toggle for iverksetting av fødselshendelse, som nå er av. For alt annet en prod ønsker vi alltid å iverksette / ikke rulle tilbake, og det er løst ved å ikke gå via unleash.

2020-11-16 10:26 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    private fun fødselshendelseSkalRullesTilbake(): Boolean {
Denne skjønte jeg ikke. Mener du at vi skal fjerne togglen?

Jeg husker ikke helt hva vi landet på, men målet var vel å skrive om toggler til å bruke aksjons-logikk der ønsket funksjonalitet slippes gjennom når togglen er på og worst case default=false.

2020-11-16 10:44 UTC, geirmundsimonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    private fun fødselshendelseSkalRullesTilbake(): Boolean {
Nei. Toggelen for å iverksette fødselshendelser er der for _prod_, og ligger i Unleash. Den er nå av, fordi vi ikke skal iverksette fødselshendelser. Vi skrur den på dersom vi ønsker å iverksette fødselshendelser.

2020-11-16 10:48 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    private fun fødselshendelseSkalRullesTilbake(): Boolean {
Nettopp, da bør vi også skrive om metodenavnene og logikken i ba-sak tenker jeg. Også kan vi sikkert legge inn en "fysisk" sperre i produksjon i kode også. Det er sansynligvis flere måneder til vi skal skru på dette og da kan vi lett fjerne koden tenker jeg. @hensol enig?

2020-11-16 12:06 UTC, hensol commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseService.kt
> +    private fun fødselshendelseSkalRullesTilbake(): Boolean {
enig med siste taler, fysisk sperre er det tryggeste siden det er lenge til dette skal skrus på.

2020-11-17 07:46 UTC, geirmundsimonsen commented on src/test/kotlin/no/nav/familie/ba/sak/behandling/fødselshendelse/FødselshendelseServiceTest.kt
>      fun `Skal iverksette behandling hvis filtrering og vilkårsvurdering passerer og toggle er skrudd av`() {
Jeg tror testen er helt fin. Skal skrives litt om ettersom vi går bort fra toggle. Men den gjør det den skal.

2020-11-20 06:59 UTC, henninghaakonsen approved these changes
Ser bra ut dette 👍

2020-11-20 06:59 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/common/EnvService.kt
> +        return environment.activeProfiles.any {
Hvis du er redd for om denne faktisk fungerer er det kanskje tryggest å alltid returnere false (siden den kun blir brukt 1 sted nå?), logge verdien også lage en ny PR etter å ha logget at verdien er riktig :)

2020-11-23 08:38 UTC, geirmundsimonsen commented on src/main/kotlin/no/nav/familie/ba/sak/common/EnvService.kt
> +        return environment.activeProfiles.any {
Fint å være på den sikre siden, ja. Deployer en versjon som ikke iverksetter for noen miljøer (unntatte e2e). Dersom det oppfører seg riktig og logger riktig, lager jeg en oppfølgings-PR.

2020-11-23 08:56 UTC, hensol approved these changes

2020-11-23 09:19 UTC, merged