Fikset feil i fødselsdato og hjemmel
navikt/familie-ba-sak pull request #779
Opened 2021-02-09 14:46 UTC by MarcusGustafson74

### 💰 Hva forsøker du å løse i denne PR'en
Fikset feil i fødselsdato (siste to fødselsnumrene skal skilles med og) og hjemmel (6 år 10, 8år 11)

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [x] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [x] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [x] Nei

2021-02-09 15:02 UTC, oyvindhagen approved these changes

2021-02-09 17:21 UTC, henninghaakonsen requested changes
Bruk funksjon som allerede benyttes.

2021-02-09 17:21 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/Person.kt
> +fun List<Person>.tilBrevTekst(): String = this.joinToString { it.fødselsdato.tilKortString() }.replaceLastDelminator("og")
Dette har vi allerede i Utils.slåSammen().

2021-02-10 07:32 UTC, henninghaakonsen approved these changes
Tenker kanskje at testen burde ligge på slåSammen funksjonen, men ikke kritisk.

2021-02-10 07:32 UTC, henninghaakonsen commented on src/test/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonTest.kt
> +internal class PersonTest{
Burde dette vært en test for slåSammen eventuelt?

2021-02-10 07:55 UTC, MarcusGustafson74 commented on src/test/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersonTest.kt
> +internal class PersonTest{
Flyttet testene til UtilsTest

2021-02-10 08:52 UTC, merged