Feature/avslag på behandling + fjerning av *_FORTSATT_INNVILGET
navikt/familie-ba-sak pull request #806
Opened 2021-02-19 09:53 UTC by henninghaakonsen

### 💰 Hva forsøker du å løse i denne PR'en
I denne PRen har er det lagt opp alle mulige permutasjoner av søknadsresultat+endring+opphør.
Det har blitt skrevet logikk for utledning av avslag og flere innvilget/endret resultater.

Jeg har også flyttet ut YtelsePersonUtils til egen fil med egne tester.
### 🔎️ Er det noe spesielt du ønsker å fremheve?
Jeg har beholdt de fleste "scenarie" testene, men flyttet litt på dem slik at testene nå er grupper slik de er listet opp på BehandlingResultat.

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [x] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [x] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

_Jeg har ikke skrevet tester fordi:_

### 🤷‍♀ ️Hvor er det lurt å starte?
Se først på behandlingsresultat, så endringene i behandlingsresultatutils.

### 💬 Ønsker du en muntlig gjennomgang?
- [ ] Ja
- [ ] Nei
Om det er ønske for det :)

2021-02-19 09:55 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
>      fun utledBehandlingsresultatBasertPåYtelsePersoner(ytelsePersoner: List<YtelsePerson>): BehandlingResultat {
Litt vanskelig å se diff her, så kan være greit å åpne opp i IntelliJ. Er litt usikker på navnene til boolean'sa, så fint om dere tar en ekstra titt på dem. Kan også hende man kan trekke ut flere booleans eller gjøre denne logikken litt smudere - åpen for forslag! :)

2021-02-19 10:00 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/domene/Behandling.kt
> + * 1. Hva er resultatet på søknaden.
```suggestion
 * 1. Hvis søknad - hva er resultatet på søknaden.
```

2021-02-19 11:55 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtils.kt
> +        val ytelsePersoner: MutableSet<YtelsePerson> =
```suggestion
        val personerFramstiltKravForINå: MutableSet<YtelsePerson> =
```

2021-02-19 11:55 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtils.kt
> +    }
nyYtelsePerson er vel egentlig gammelYtelsePerson som skal legges til med et false-flagg. Det er heller ikke så tydelig her at contains ser på hash av kun ident og type.

Er det enklere å forstå som noe sånt? 

```suggestion
val personerFramstiltKravForITidligere: List<YtelsePerson> = forrigeAndelerTilkjentYtelse.map{ it.tilYtelsePerson(it.personident, it.type)}
```

Hvor man på AndelTilkjentYtelse lager extension
```
fun tilYtelsePerson(erFramstiltKravForINåværendeBehandling: Boolean = false) =
            YtelsePerson(personIdent = this.personIdent,
                         ytelseType = this.type,
                         erFramstiltKravForINåværendeBehandling = erFramstiltKravForINåværendeBehandling)
```

og til slutt her returner noe lignende
`return listOf(personerFramstiltKravForINå, personerFramstiltKravForTidligere.filter(!personerFramstiltKravForINå.contains(it)).flatten()`

2021-02-19 11:55 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtils.kt
> +    }
ikke sikkert det er så mye mer lesbart kanskje :P

2021-02-19 11:59 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtils.kt
> +    }
Nå er dette ren flytting, men jeg kan ta en titt 💪

2021-02-19 12:11 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtils.kt
> +            ytelsePerson.erFramstiltKravForINåværendeBehandling && segmenterLagtTil.isEmpty
Sånn sett er det kanskje mer passende å si
finnesAvslagPåSøknad/YtelsePerson
finnesInnvilgetSøknad/YtelsePerson

? 🤔

2021-02-19 12:19 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/YtelsePersonUtils.kt
> +                                           andeler: List<AndelTilkjentYtelse>,
```suggestion
                                           andeler: List<AndelTilkjentYtelse>,
```
er ikke dette oppdatert tilstand? uansett holder kanskje resterende sjekker :)

2021-02-19 14:01 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +                erAvslått && !erEndring && !erNoeFraTidligereBehandlingerSomOpphører ->
`val erAvslått = framstiltNå.flatMap { it.resultater }.all { it == YtelsePersonResultat.AVSLÅTT }
`
lurer på om vi må endre logikken for erAvslått. Det er kun denne som egentlig kan slå til nå av avslått-casene? Siden det aldri vil finnes noe annet enn AVSLÅTT

2021-02-19 14:06 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +                erAvslått && !erEndring && !erNoeFraTidligereBehandlingerSomOpphører ->
Det stemmer nok, men det kan tas i egen PR tenker jeg. Fordi det går vel på å utvide YtelsePerson til å få flere resultater ikkesant?

2021-02-19 16:16 UTC, oyvindhagen requested changes
Synes det er gjort veldig mye bra her for å gjøre koden mer lesbar og forståelig. 👍 
Finner bare en ting å sette fingeren på, og det kan vi gjerne ta en prat om på mandag om ønskelig.

2021-02-19 16:16 UTC, oyvindhagen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +            throw Feil(message = "Minst én ytelseperson har fått opphør som resultat uten å ha periodeStartForRentOpphør satt")
Jeg tror dette kan bli feil slik det er kodet nå. Dersom ytelsen er opphørt så settes likevel ikke periodeStartForRentOpphør dersom en finner at det er fjernet andeler med tom som er før tom for den siste andelen i tidslinja (altså den som gjør at vi har et opphør.) Ref. linje 110 i YtelsePersonUtils.  
```
if (segmenterFjernet.any { it.tom.toYearMonth() < innvilgetAndelTom }) {
    null
}...
```

2021-02-22 07:13 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +            throw Feil(message = "Minst én ytelseperson har fått opphør som resultat uten å ha periodeStartForRentOpphør satt")
Ok, skjønner. Så dette feltet blir kun satt om det er reduksjon på personen?

2021-02-22 08:02 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +                erAvslått && !erEndring && !erNoeFraTidligereBehandlingerSomOpphører ->
Ønsker vi oss ikke logikken du beskriver? Dersom det også finnes noe som er innvilget betyr det jo at resultatet er “delvis innvilget”.

2021-02-22 08:14 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +                erAvslått && !erEndring && !erNoeFraTidligereBehandlingerSomOpphører ->
Det kan hende vi ønsker oss det, men da må vi også ha en egen finnesAvslått eller lignende som ikke _kun_ tar høyde for at alt er avslått. Sånn som det er nå vil jo aldri f.eks `erAvslått && erEndring && alleOpphørt ` kunne skje, siden ` && erEndring && alleOpphørt ` implisitt er false når er(ALLE)Avslått. Så sjekkene stemmer liksom ikke med logikken per nå?

2021-02-22 08:24 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +                erAvslått && !erEndring && !erNoeFraTidligereBehandlingerSomOpphører ->
Men den sjekker jo kun på framstiltNå, altså søknaden. Så totalresultatet for søknad er avslag kun når alle resultatene fra søknaden er avslag.

2021-02-22 08:25 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +                erAvslått && !erEndring && !erNoeFraTidligereBehandlingerSomOpphører ->
Vi kunne gjort det mer eksplisitt ved å si:
erInnvilget -> erSøknadInnvilget
erAvslått -> erSøknadAvslått
erDelvisInnvilget -> erSøknadDelvisInnvilget

2021-02-22 08:28 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +                erAvslått && !erEndring && !erNoeFraTidligereBehandlingerSomOpphører ->
Det er ikke delvis innvilget jeg snakekr om, det er de andre avslått-resultatene, f.eks. det nevnt i kommentaren. Vi kan ta det muntlig hvis du vil

2021-02-22 09:34 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +                erAvslått && !erEndring && !erNoeFraTidligereBehandlingerSomOpphører ->
My bad som ikke leser skikkelig her 🙈  resolver denne 👍

2021-02-22 09:37 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatUtils.kt
> +            throw Feil(message = "Minst én ytelseperson har fått opphør som resultat uten å ha periodeStartForRentOpphør satt")
Har hvertfall fjernet asserten :)

2021-02-22 09:39 UTC, oyvindhagen approved these changes

2021-02-22 09:43 UTC, merged