Feature/migrering
navikt/familie-ba-sak pull request #891
Opened 2021-03-19 15:35 UTC by tnarland

### 💰 Hva forsøker du å løse i denne PR'en
Forsøker å løse backend-delen av migrering MVP'en slik det er skissert i blokken markert "BA-sak backend" i 
[Mural](https://app.mural.co/t/navdesign3580/m/navdesign3580/1614860629682/aa8ea40a716cfc530bfe36b427c10a92575d491b).

### 🔎️ Er det noe spesielt du ønsker å fremheve?
La først til en ny BehandlingÅrsak kalt MIGRERING, men har senere endret behandlingsårsaken til NYE_OPPLYSNINGER, siden det er ved mottak av ettersendelse migreringsfunksjonen først tas i bruk. Den nye behandlingsårsaken er dermed ubrukt kode, og fungerer heller ikke med mindre den også legges til i stønadsstatistikk-kontrakten. Men der opplyser vi allerede om BEHANDLINGS_TYPE=MIGRERING_FRA_INFOTRYGD, så den er strengt tatt ikke nødvendig og kan kanskje fjernes inntil videre

### ✅ Checklist
_Har du husket alle punktene i listen?_
- [x] Jeg har testet mine endringer i henhold til akseptansekriteriene 🕵️
- [x] Jeg har skrevet tester. Hvis du ikke har skrevet tester, beskriv hvorfor under 👇

### 🤷‍♀ ️Hvor er det lurt å starte?
Kan f.eks starte fra "migrer"-funksjonen i MigreringService og sammenligne kodeflyten med skissen i Mural.

### 💬 Ønsker du en muntlig gjennomgang?
- [x] Ja
- [ ] Nei

2021-03-22 07:59 UTC, MarcusGustafson74 commented on src/test/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringServiceTest.kt
> +    @Test
Skal den tagges med @Tag("integration")

2021-03-22 12:30 UTC, tnarland commented on src/test/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringServiceTest.kt
> +    @Test
Det kan den sikkert. Hva gjør den tag'en?

2021-03-24 08:24 UTC, ninakjek reviewed
![image](https://user-images.githubusercontent.com/5719550/112277015-9d243e00-8c81-11eb-88fa-169b472b9399.png)
Veldig bra jobba! Supert med muntlig gjennomgang og fint med lenke til oversiktlig mural i pr :) et par små kommentarer, men bare pirk, så dere kan se om dere er enige og evt vil gjøre noe med det. Når småtinga fra den muntlige gjennomgangen er på plass (trekke ut konstanter, kanskje fikse totrinns, ta inn årsak som param, evt e2e) er nok dette good to go!

2021-03-24 08:24 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +            val beløpFraInfotrygd = løpendeSak.stønad!!.delytelse.first().beløp.toInt()
Her kan jeg begynne å lure på om vi velger den første fra datosortert delytelse, men egentlig er det vel her antatt at det er én? Hvis det er tilfellet, kan man tydeliggjøre det vel å bruke singleOrNull? 
```suggestion
            val beløpFraInfotrygd = løpendeSak.stønad!!.delytelse.singleOrNull()?.beløp?.toInt() ?: error("Finnes flere delytelser på sak")
```

2021-03-24 08:24 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +        val barnasIdenter = løpendeSak.stønad!!.barn
Ser at `løpendeSak.stønad!!` kalles flere steder. Det er kanskje lite sannsynlig at sjekken tidligere i løpet endres/ikke kommer til å kalles, men kan man gjøre koden enda mer robust ved å enten kaste beskrivende feil eller bare sende inn det man trenger som ikke nullables? Ser f.eks her og i `sammenlignTilkjentYtelseMedBeløpFraInfotrygd` (kanskje flere steder?) at man egentlig bare trenger stønad, så kanskje man kan ta inn en ikke nullable stønad i disse funksjonene.

2021-03-24 09:09 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringController.kt
> +@RequestMapping("/api/infotrygd")
InfotrygdController har samme requstMapping verdi. Burde de vært samlet eller hatt forskjellig url?

2021-03-24 12:36 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +            if (this.year != 2021) throw Feil("Migrering feilet: Kopien av Infotrygds kjøreplan er utdatert.",
Hva gjør vi i 2022?

2021-03-24 12:40 UTC, stigebil commented on src/test/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringServiceTest.kt
> +    fun `migrering happy case`() {
Burde det vært en egen test med hva man sender til datavarehus?

2021-03-24 12:44 UTC, stigebil commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +                                                                      skalBehandlesAutomatisk = false,
Bør være true hvis dette er automatisk? Eller er det ikke akkurat her? Siden den starter fra gui.

2021-03-24 12:46 UTC, stigebil approved these changes

2021-03-26 10:00 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +            val beløpFraInfotrygd = løpendeSak.stønad!!.delytelse.first().beløp.toInt()
👍

2021-03-26 11:17 UTC, henninghaakonsen requested changes
Veldig bra jobba - tror vi bør gjøre noen flytendringer blant annet 👍

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/grunnlag/personopplysninger/PersongrunnlagService.kt
> +        if (behandling.skalBehandlesAutomatisk && !behandling.erMigrering()) {
Bra 👍

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatService.kt
> +                if (behandling.opprettetÅrsak == BehandlingÅrsak.FØDSELSHENDELSE || behandling.erMigrering()) {
Gir det mer mening å bare droppe hele utledningen av behandlingsresultat og bare sette det manuelt for migreringsbehandlinger? Mulig man ønsker et eget resultat for disse behandlingene som f.eks. `FORTSATT_INNVILGET_AUTOMATISK` eller noe?

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
Hva er tanken her? Tror ikke vi ønsker å iverksette uansett om resultatet er fortsatt innvilget.

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
>      private fun genererInitieltBehandlingResultat(behandling: Behandling): Vilkårsvurdering {
```suggestion
    private fun genererInitiellVilkårsvurdering(behandling: Behandling): Vilkårsvurdering {
```

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
> +                val begrunnelse = "Migrering"
Er dette ønsket begrunnelse?

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
> +                val tom: LocalDate? =
Er dette kopiert? Isåfall tenker jeg det er fint å lage felles funksjon for dette :)

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +    private fun kastFeilDersomAlleredeMigrert(fagsak: Fagsak) {
Generelt bør vi bruke FunksjonellFeil eller populere frontendFeilmelding om vi ønsker melding til bruker.

Virker som ganske spesifikke feilmeldinger, så bør sikkert testes ganske nøye med fag - samt ha enhetstester.

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +            else -> throw FunksjonellFeil("Kan kun migrere ordinære saker med nøyaktig ett utbetalingsbeløp. Fant $antallBeløp.",
Fint å bruke named parameters her tenker jeg :)

2021-03-26 11:17 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +            return when (this.month) {
Lurer på om @oyvindhagen også trenger dette, kunne/burde det ligget i en util-fil?

2021-03-26 11:57 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
Det er i praksis ingen endring ift. resultat fortsatt innvilget her. Iverksett-steget skippes da som normalt. Tanken var at det for andre resultater av automatisk behandling er naturlig å gå videre til iverksetting, i og med at statusen til "IVERKSETTER_VEDTAK" over.

2021-03-26 11:59 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
Ahh, godt poeng. Men kanskje det uansett gir mening å skippe iverksetting når resultatet er FORTSATT_INNVILGET? cc @ninakjek @oyvindhagen

2021-03-26 12:32 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatService.kt
> +                if (behandling.opprettetÅrsak == BehandlingÅrsak.FØDSELSHENDELSE || behandling.erMigrering()) {
Det kan hende. Vi må bare sørge for at resultatet forblir "IKKE_VURDERT" inntil vi setter det manuelt, ellers påvirker det logikken underveis. F.eks skippes iverksett-steget vis resultatet er "FORTSATT_INNVILGET".

2021-03-26 12:38 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
tror vi effektivt skipper iverksetting for resultat FORTSATT_INNVILGET allerede, siden vi da returner StegType.JOURNALFØR_VEDTAKSBREV, som er steget etter iverksetting, hvis jeg ikke husker feil

2021-03-26 12:43 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/vilkår/VilkårService.kt
> +                val tom: LocalDate? =
Jaa, delvis. Skal se det er noe som kan trekkes ut :)

2021-03-26 13:55 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +            if (this.year != 2021) throw Feil("Migrering feilet: Kopien av Infotrygds kjøreplan er utdatert.",
oppdaterer ihht. Infotrygds kjøreplan for 2022 når den er klar antar jeg

2021-03-26 14:37 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatService.kt
> +                if (behandling.opprettetÅrsak == BehandlingÅrsak.FØDSELSHENDELSE || behandling.erMigrering()) {
Kunne vi f.eks lagt til
`        if (ytelsePersoner.isEmpty()) return BehandlingResultat.IKKE_VURDERT`

i funksjonen utledBehandlingsresultatBasertPåYtelsePersoner?

2021-04-06 07:50 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/resultat/BehandlingsresultatService.kt
> +                if (behandling.opprettetÅrsak == BehandlingÅrsak.FØDSELSHENDELSE || behandling.erMigrering()) {
Hmm, litt usikker. Er ikke det enkleste å bare legge til noe sær-logikk i vilkårsvurderingssteget? Hvis det er en migreringsbehandling så kaller vi bare ikke utledBehandlingsresultat metoden :)

2021-04-06 07:50 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
Ja, det er mulig 👍  Men vi skal ikke sende ut brev ved fortsatt innvilget heller, men det er kanskje for en annen oppgave ;)

2021-04-06 10:13 UTC, ninakjek commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
jepp, hvis det er behov for ytterligere håndtering for fortsatt_innviget er det sikkert greit å ta det i en egen oppgave. Kanskje du kan lage en oppgave på det tor? evt håndtere ved å sende til rett steg, om det ikke er mer som skal til

2021-04-06 19:03 UTC, oyvindhagen commented on src/main/kotlin/no/nav/familie/ba/sak/infotrygd/MigreringService.kt
> +            return when (this.month) {
Tenker du på kjøreplanen til økonomi i forbindelse med simulering og oppdatering av denne @henninghaakonsen? I så fall ser det ut til at vi ikke trenger å forholde oss til den likevel. Vi kan sannsynligvis bruke forfallsdato på simuleringsposteringene i stedet. Hvis ikke hadde vi gjerne tatt imot en util-funksjon for dette med åpne armer :)

2021-04-08 08:18 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
Git-historikken viser at det ble lagt til i feature/autobrev, så mulig det er riktig at det skal sendes brev ved fortsatt_innvilget etter automatisk behandling ifm. omregning ved 6 og 18 år. Burde det vært en betingelse basert på behandligÅrsak i tillegg? @MarcusGustafson74 @oyvindhagen

2021-04-08 08:19 UTC, henninghaakonsen commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
Godt poeng!

2021-04-08 08:35 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/SimuleringSteg.kt
> +            return when (behandling.resultat) {
lagt til manglende steglogikk fra vilkårsvurderingSteg slik at simulering ikke skal påvirke flyten videre

2021-04-08 08:54 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt
> +                             totrinnsbehandling = !behandling.skalBehandlesAutomatisk,
Fant en bug her, men litt usikker på om
`totrinnsbehandling = !behandling.skalBehandlesAutomatisk`
er riktig i alle tilfeller. Vurderte også
`totrinnskontroll?.saksbehandler?.let { it != SYSTEM_NAVN } ?: false`

2021-04-08 10:01 UTC, henninghaakonsen approved these changes
Har veldig full kalender så vil ikke være noe brems så auto-approver denne. Stoler på at det er bra uansett 👍

2021-04-08 11:55 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/saksstatistikk/SaksstatistikkService.kt
> +                             totrinnsbehandling = !behandling.skalBehandlesAutomatisk,
Går for
`totrinnsbehandling = !behandling.skalBehandlesAutomatisk`
etter å ha forhørt meg med Eivind

2021-04-08 12:07 UTC, tnarland commented on src/main/kotlin/no/nav/familie/ba/sak/behandling/steg/VilkårsvurderingSteg.kt
> +        return hentNesteStegForNormalFlyt(behandling)
Jeg kan lage en oppgave på det :)

2021-04-08 12:32 UTC, merged